- name: Install Docker and start Mariadb
  hosts: local
  tasks:
  - name: install docker package
    apt:
      name: docker-ce
      state: present
  - name: Start docker service
    service:
      name: docker
      state: started
  - name: Start mariadb service
    service:
      name: mariadb
      state: started